version: '3.7'
services:
  web:
    image: "django-demo:dev"
    build:
      target: development_build
      context: .
      cache_from:
        - "django-demo:dev"
        - "django-demo:latest"
        - "*"
      args:
        DJANGO_ENV: development
    command: /bin/bash -c "sleep 7; python -Wd manage.py migrate; python -Wd manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev