version: '3.7'
services:
  web:
    build:
      target: development_build
      context: .
      args:
        DJANGO_ENV: development
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    command: /bin/bash -c "sleep 30; python -Wd manage.py migrate; python -Wd manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev